server:
  port: 9003
spring:
  application:
    name: bailis-qa #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.232.132:3306/bls_qa?serverTimezone=GMT%2b8&useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true